version: '3'

services:
  spring-boot-admin:
    build:
      context: ./spring-admin
    ports:
      - "8765:8765"
    environment:
      - EUREKA_DEFAULT_ZONE=http://spring-eureka:8761/eureka/
    depends_on:
      - spring-eureka

  spring-eureka:
    build:
      context: ./spring-eureka
    ports:
      - "8761:8761"